package cch.importTool.dao;

import cch.importTool.model.LegalPerson;
import cch.importTool.model.LegalPersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LegalPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    int countByExample(LegalPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    int deleteByExample(LegalPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    int insert(LegalPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    int insertSelective(LegalPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    List<LegalPerson> selectByExample(LegalPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    LegalPerson selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") LegalPerson record, @Param("example") LegalPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    int updateByExample(@Param("record") LegalPerson record, @Param("example") LegalPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    int updateByPrimaryKeySelective(LegalPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LegalPerson
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    int updateByPrimaryKey(LegalPerson record);
}