package cch.importTool.model;

import java.util.Date;

public class LegalPerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.Id
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.PersonName
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.PersonIdCardNum
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String personIdCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.Mobile
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.Password
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.CompanyName
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.CompanyIdNum
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String companyIdNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.CompanyType
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.ImportTag
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String importTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.ImportTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private Date importTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.Result
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LegalPerson.UpdateTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.Id
     *
     * @return the value of LegalPerson.Id
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.Id
     *
     * @param id the value for LegalPerson.Id
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.PersonName
     *
     * @return the value of LegalPerson.PersonName
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.PersonName
     *
     * @param personName the value for LegalPerson.PersonName
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.PersonIdCardNum
     *
     * @return the value of LegalPerson.PersonIdCardNum
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getPersonIdCardNum() {
        return personIdCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.PersonIdCardNum
     *
     * @param personIdCardNum the value for LegalPerson.PersonIdCardNum
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setPersonIdCardNum(String personIdCardNum) {
        this.personIdCardNum = personIdCardNum == null ? null : personIdCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.Mobile
     *
     * @return the value of LegalPerson.Mobile
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.Mobile
     *
     * @param mobile the value for LegalPerson.Mobile
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.Password
     *
     * @return the value of LegalPerson.Password
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.Password
     *
     * @param password the value for LegalPerson.Password
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.CompanyName
     *
     * @return the value of LegalPerson.CompanyName
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.CompanyName
     *
     * @param companyName the value for LegalPerson.CompanyName
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.CompanyIdNum
     *
     * @return the value of LegalPerson.CompanyIdNum
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getCompanyIdNum() {
        return companyIdNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.CompanyIdNum
     *
     * @param companyIdNum the value for LegalPerson.CompanyIdNum
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setCompanyIdNum(String companyIdNum) {
        this.companyIdNum = companyIdNum == null ? null : companyIdNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.CompanyType
     *
     * @return the value of LegalPerson.CompanyType
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.CompanyType
     *
     * @param companyType the value for LegalPerson.CompanyType
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType == null ? null : companyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.ImportTag
     *
     * @return the value of LegalPerson.ImportTag
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getImportTag() {
        return importTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.ImportTag
     *
     * @param importTag the value for LegalPerson.ImportTag
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setImportTag(String importTag) {
        this.importTag = importTag == null ? null : importTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.ImportTime
     *
     * @return the value of LegalPerson.ImportTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public Date getImportTime() {
        return importTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.ImportTime
     *
     * @param importTime the value for LegalPerson.ImportTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.Result
     *
     * @return the value of LegalPerson.Result
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.Result
     *
     * @param result the value for LegalPerson.Result
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LegalPerson.UpdateTime
     *
     * @return the value of LegalPerson.UpdateTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LegalPerson.UpdateTime
     *
     * @param updateTime the value for LegalPerson.UpdateTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}