package cch.importTool.model;

import java.util.Date;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.Id
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.Name
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.IdCardNum
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String idCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.Mobile
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.Password
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.ImportTag
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String importTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.ImportTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private Date importTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.Result
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.UpdateTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.Id
     *
     * @return the value of Person.Id
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.Id
     *
     * @param id the value for Person.Id
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.Name
     *
     * @return the value of Person.Name
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.Name
     *
     * @param name the value for Person.Name
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.IdCardNum
     *
     * @return the value of Person.IdCardNum
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getIdCardNum() {
        return idCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.IdCardNum
     *
     * @param idCardNum the value for Person.IdCardNum
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setIdCardNum(String idCardNum) {
        this.idCardNum = idCardNum == null ? null : idCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.Mobile
     *
     * @return the value of Person.Mobile
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.Mobile
     *
     * @param mobile the value for Person.Mobile
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.Password
     *
     * @return the value of Person.Password
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.Password
     *
     * @param password the value for Person.Password
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.ImportTag
     *
     * @return the value of Person.ImportTag
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getImportTag() {
        return importTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.ImportTag
     *
     * @param importTag the value for Person.ImportTag
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setImportTag(String importTag) {
        this.importTag = importTag == null ? null : importTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.ImportTime
     *
     * @return the value of Person.ImportTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public Date getImportTime() {
        return importTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.ImportTime
     *
     * @param importTime the value for Person.ImportTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.Result
     *
     * @return the value of Person.Result
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.Result
     *
     * @param result the value for Person.Result
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.UpdateTime
     *
     * @return the value of Person.UpdateTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.UpdateTime
     *
     * @param updateTime the value for Person.UpdateTime
     *
     * @mbggenerated Sun Dec 02 15:36:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}